mod app;
mod config;
mod feed;
mod gap;
mod grouping;
mod imsa_widths;
mod pit;
mod popups;
mod render;
mod render_class;
mod render_favourites;
mod render_grouped;
mod render_overall;
mod render_utils;
mod search;
mod series_widths;
mod style;
mod table;
mod table_builder;
mod table_utils;
mod table_widths;
mod wec_widths;
mod width_math;
mod width_state;

pub use app::run_app;
